### ISSUE TITLE
Add Data scraping for Warren County

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/ohio#4]
Add ability to scrape property data. Test solution.
This issue represents all sub-issues to process Warren County.

**Comment by ludstuen90** [comment]
Installed Scrapy. Required installing additional plugins via MacOSX. (See https://twistedmatrix.com/trac/wiki/Downloads )

**Comment by ludstuen90** [comment]
@walinchus 

* For storing school district information, would you like to see School District ID? (eg. 8305) or full name? (eg. LEBANON CSD)
* When we store 'current market value,' would you like to see the 2017 value, or 2018 tentative value? 
* When storing CAUV property (true/false value), can we assert that if there is a dollar figure listed for a CAUV  tax value, then it is a CAUV property? If so, should we use the 2017 or 2018 value? (If not, do you know where we'd find it?) 
![image](https://user-images.githubusercontent.com/6817579/48719940-621b2700-ebfd-11e8-81a7-d97f1a341486.png)
From this page: http://www.co.warren.oh.us/property_search/summary.aspx?account_nbr=6150660

* Confirming the "land use code" would be the state use code (i.e. 0510 - SINGLE FAMILY DWG (PLATTED))

It looks like the following fields aren't available online for Warren county: 
* tax_lien
* mortgage_amount
* date_of_mortgage
* rental_registration (Closest I see is 'owner occupied,' but I'm not sure from there we can extrapolate a rental registration)
* date_of_LLC_name_change


I do see we have sale history that generate conveyance numbers: 
![image](https://user-images.githubusercontent.com/6817579/48724832-19696b00-ec09-11e8-887d-556d82481b84.png)

How does this look?

**Comment by walinchus** [comment]
- Is there a way to store the name as well as the ID number? Ohio is one of the few states that has a tax BY school district. So when you're doing your taxes, you actually have to look up your school district, write down the number, and it generates an amount owed. 

- Ideally current _and_ tentative if possible. That will help to track the valuations over time. 

- CAUV is essentially a tax incentive for farmland. If you want to use the farmland as a farm, they will tax it at the value of a farm. the CAUV value.  Not the value that a developer would pay to take the farmland and turn it into houses or stores or whatever. So yes that makes if CAUV property. 

- Yes Ohio at least has consistent land use codes. Here they are: http://codes.ohio.gov/oac/5703-25-10

- Some records we might have to get from other places. For example, it looks like in warren county liens are recordered at the county recorder. 

![screen shot 2018-11-19 at 1 21 25 pm](https://user-images.githubusercontent.com/25959269/48726874-a5c26080-ebfe-11e8-83c5-0137da91f391.png)

You can see here from the screen shot, the lien is the "consideration", recorded date is the date_of_mortgage, etc. 

- LLC name changes will be in the secretary of state's website. Looks like it's form 558 to change your name. But to look them up it looks like it's a search that doesn't allow for wildcards. (I tried B558* because B558 would be the beginning of the document number. 

I wonder if it might be more useful to search by canceled/dissolved corporations? https://hb48.sos.state.oh.us/

-conveyance numbers might be helpful for our purposes to keep things straight as I'm sure there are quite a few similar ones. Before digital records, it was actually the book number and page number, although now I believe it's the date and number of transaction. If this is too much, we could just track the conveyance of large properties over time. I don't think tracking the value of individual homes woudl be as useful. 

-If it hasn't been checked "owner occupied" there's a good chance it's a rental. (Unless it's someone's second home.)

**Comment by ludstuen90** [comment]
Scraping for a Warren County record is partially up. We have some difficulties with Tax Address and the following fields are not scraped yet: 
```
tax_lien
cauv_property
rental_registration
owner_address
date_of_LLC_name_change
date_of_LLC_name_change
date_of_mortgage
mortgage_amount
property_class
```
